# Section 1.4 $\quad$ Algebraic Properties of Matrix Operations

## 1. Properties of Matrix Addition

Let $A$, $B$, and $C$ be $m\times n$ matrices <br />
- $A+B = $
- $A+(B+C)=$
- There is a unique $m\times n$ **zero matrix**, denoted by $O$, such that
<br /><br /><br /><br />
- For each $m\times n$  matrix $A$, there is a unique $m\times n$ matrix $D$ such that
<br /><br /><br /><br />

## 2. Properties of Matrix Multiplication

Let $A$, $B$, and $C$ be matrices of appropriate sizes.
- $A(BC) = $
- $(A+B)C = $
- $C(A+B) = $
<br /><br />
**Remark:** <br /><br /><br /><br />

### Example 1

Let
$$
  A = \left[
        \begin{array}{ccc}
          2 & 2 & 3 \\
          3 & -1 & 2 \\
        \end{array}
      \right],~~~~
  B = \left[
        \begin{array}{ccc}
          0 & 0 & 1\\
          2 & 3 & -1\\
        \end{array}
      \right],~~~\text{and}~~~
  C = \left[
        \begin{array}{cc}
          1 & 0 \\
          2 & 2 \\
          3 &-1 \\
        \end{array}
      \right]
$$
Compute $(A+B)C$ and $AC+BC$.

In [1]:
from numpy import *

A = array([[2, 2, 3], [3, -1, 2]]);
B = array([[0, 0, 1], [2, 3, -1]]);
C = array([[1, 0], [2, 2], [3, -1]]);

dot(A + B, C)

array([[18,  0],
       [12,  3]])

In [2]:
from numpy import *

A = array([[2, 2, 3], [3, -1, 2]]);
B = array([[0, 0, 1], [2, 3, -1]]);
C = array([[1, 0], [2, 2], [3, -1]]);

dot(A, C) + dot(B, C)

array([[18,  0],
       [12,  3]])

## 3. Properties of Scalar Multiplication

Let $r$ and $s$ be real numbers. Let $A$ and $B$ be matrices of appropriate sizes.
- $r(sA) =$
- $(r+s)A = $
- $r(A+B) = $
- $A(rB) = $

## 4. Properties of Transpose

Let $r$ and $s$ be real numbers. Let $A$ and $B$ be matrices of appropriate sizes.
- $(A^T)^T =$
- $(A+B)^T = $
- $(AB)^T = $
- $(rA)^T = $

**Questions** <br />
- Does $A^2 = O $ imply $A = O$?
  <br /><br /><br /><br />
- Does $AB = AC$ imply $B = C$?
  <br /><br /><br /><br />

# Section 1.5 $\quad$ Special Types of Matrices

## Diagonal Matrices

- An $n\times n$ matrix $A = [a_{ij}]$ is called a $\underline{\hspace{1.5in}}$ if
<br /><br /><br /><br />
    **Question:** Is the zero matrix $O$ a diagonal matrix?
<br /><br /><br /><br />
- If the diagonal elements of a diagonal matrix are equal, we call it a $\underline{\hspace{1.5in}}$.
- If the diagonal elements of a diagonal matrix and are equal to $1$, we call it a
    $\underline{\hspace{1.5in}}$ and write it as $\underline{\hspace{1in}}$.
<br /><br />
    **Property:** $A I_n = $ $\hspace{1.5in}$ $I_m A = $
<br /><br /><br /><br /><br /><br /><br />

## Symmetric Matrices

- An $n\times n$ matrix $A = [a_{ij}]$ is called $\underline{\hspace{1.5in}}$ if
<br /><br /><br /><br />
    It is called $\underline{\hspace{2in}}$ if
<br /><br /><br /><br />
- matrix $A$ with real entries is called $\underline{\hspace{1.5in}}$ if $\underline{\hspace{1.5in}}$.
- A matrix $A$ with real entries is called $\underline{\hspace{2in}}$ if $\underline{\hspace{1.5in}}$.
<br />
    **Property:** Every square matrix can be decomposed as the sum of a symmetric matrix and a skew symmetric matrix.
<br /><br />
    **Proof:**
<br /><br /><br /><br /><br /><br /><br />

## Nonsingular Matrices

An $n\times n$ matrix $A$ is called $\underline{\hspace{1.5in}}$ or $\underline{\hspace{1.5in}}$ if
<br /><br /><br /><br />

Such a matrix $B$ is called an $\underline{\hspace{1.5in}}$ of $A$ and denoted by $\underline{\hspace{1in}}$.
<br /><br /><br /><br />

If $A$ is not invertible, we call it $\underline{\hspace{1.5in}}$ or $\underline{\hspace{1.5in}}$.
<br /><br /><br /><br />

>**Theorem** The inverse of a matrix, if

**Proof:**
<br /><br /><br /><br /><br /><br /><br />

### Example 2

Let
$$
  A = \left[
        \begin{array}{cc}
          1 & 2  \\
          3 & 4 \\
        \end{array}
      \right],~~~~~~~
  B = \left[
        \begin{array}{cc}
          1 & 2  \\
          2 & 4 \\
        \end{array}
      \right]
$$
Find the inverse $A^{-1}$ and $B^{-1}$, if they exist.

In [3]:
from numpy import *

A = array([[1, 2], [3, 4]]);

linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [4]:
from numpy import *

B = array([[1, 2], [2, 4]]);

linalg.inv(B)

LinAlgError: Singular matrix

## Properties of Inverse

- $(A^{-1})^{-1} = $
- $(AB)^{-1} = $
- $(A^T)^{-1} = $

## Application to Linear System

If $A$ is an $n\times n$ matrix, then the linear system $A\mathbf{x} = \mathbf{b}$ is a system of $n$ equation in $n$ unknowns.